spring:
  application:
    name: spring-netty-integration
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

server:
  port: 8080
  servlet:
    context-path: /netty-demo

# Netty服务器配置
netty:
  server:
    port: 8888
    boss-threads: 1
    worker-threads: 4
  client:
    host: localhost
    port: 8888
    username: demo-user

# 日志配置
logging:
  level:
    root: INFO
    io.github.yaojiqunaer.netty: DEBUG 